// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn9FATDxnCt_I5WJ86qBaZFFvjh5QxQrM',
    appId: '1:942708541670:web:1e7002378bdbe1bfa89327',
    messagingSenderId: '942708541670',
    projectId: 'sportguider-60179',
    authDomain: 'sportguider-60179.firebaseapp.com',
    storageBucket: 'sportguider-60179.firebasestorage.app',
    measurementId: 'G-NSJ7J6TJ3Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaMfOTl4vIPEHrB2T5es-hGlJnoECcGXA',
    appId: '1:942708541670:ios:0be15254b3a09ed0a89327',
    messagingSenderId: '942708541670',
    projectId: 'sportguider-60179',
    storageBucket: 'sportguider-60179.firebasestorage.app',
    iosBundleId: 'com.example.sportguider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn9FATDxnCt_I5WJ86qBaZFFvjh5QxQrM',
    appId: '1:942708541670:web:ed0b868805ff44f4a89327',
    messagingSenderId: '942708541670',
    projectId: 'sportguider-60179',
    authDomain: 'sportguider-60179.firebaseapp.com',
    storageBucket: 'sportguider-60179.firebasestorage.app',
    measurementId: 'G-GCJTBGP7VP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2HkRmmJEybBxw65k8p_hr7-ABWS6XZ-0',
    appId: '1:926946729098:ios:64fc87038499c5dd45e173',
    messagingSenderId: '926946729098',
    projectId: 'sportguider-cfd1d',
    storageBucket: 'sportguider-cfd1d.firebasestorage.app',
    iosBundleId: 'com.example.sportguider',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCplfT755gdMjrlOz0lyBM3LShNCiEatt0',
    appId: '1:926946729098:android:c4e1a8d234277e9045e173',
    messagingSenderId: '926946729098',
    projectId: 'sportguider-cfd1d',
    storageBucket: 'sportguider-cfd1d.firebasestorage.app',
  );

}